table ROE
	lineageTag: 6b5f2d29-8ad2-4e8c-9812-dbc459cd04fd

	column Company
		dataType: string
		lineageTag: 60637a48-cf9a-493b-85f8-1311d03da2bb
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column ROE
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 23e08caf-0070-429a-8ed2-b71758a4da4f
		summarizeBy: sum
		sourceColumn: ROE

		annotation SummarizationSetBy = Automatic

	partition ROE = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\madhu\Videos\Costco Data\ratios.xlsx"), null, true),
				    Table3_Table = Source{[Item="Table3",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table3_Table,{{"Company", type text}, {"ROE", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

