table SPY
	lineageTag: 19435e4b-8c59-4cde-bc28-c0d106c1cba1

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: e04929f8-3dba-4e9c-9372-b2b83a90e099
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: double
		lineageTag: 2002c02a-6223-4aab-986b-5b6a36e31880
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: dc83cce7-65d1-4e80-95ad-442c99e7814a
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 2433bdc7-5274-4164-a3c7-2544f579592b
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 5d927b5e-0cdc-4c65-8d5e-6e5d27db2608
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 75388ae7-8f8e-40c0-86d2-7354e29ec6be
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition SPY = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\madhu\Videos\Costco Data\costco_data.xlsx"), null, true),
				    SPY_Sheet = Source{[Item="SPY",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(SPY_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type datetime}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

